export const katechonTheme = {
    bg: "#050608",
    panel: "rgba(9, 12, 15, 0.72)",
    panelStrong: "rgba(8, 11, 14, 0.9)",
    line: "rgba(242,244,247,0.12)",
    lineHot: "rgba(0,232,123,0.58)",
    text: "#f2f4f7",
    muted: "rgba(242,244,247,0.64)",
    soft: "rgba(242,244,247,0.36)",
    green: "#00e87b",
    cyan: "#7de8ff",
    amber: "#ffbd2e",
    red: "#ff5f57",
};

export const katechonDeck = [
    {
        title: "SPECTRE OSINT",
        workspace: "Remote Desktop",
        operator: "Kat",
        briefing: "Watching the signal layer for movement, corroboration, and analyst-grade context.",
        signal: "INTEL",
        cadence: "LIVE",
        confidence: 91,
        accent: katechonTheme.green,
        lens: "source triage",
    },
    {
        title: "World Monitor",
        workspace: "Geopolitical Mesh",
        operator: "Kat",
        briefing: "Maps, briefs, market context, and risk pressure gradients stay side by side.",
        signal: "RISK",
        cadence: "24H",
        confidence: 84,
        accent: katechonTheme.cyan,
        lens: "correlation",
    },
    {
        title: "Glance Board",
        workspace: "News + Markets",
        operator: "Kat",
        briefing: "A clean surface for feeds, weather, clips, and the few signals worth pulling forward.",
        signal: "SCAN",
        cadence: "NOW",
        confidence: 88,
        accent: "#d9ffe9",
        lens: "source hygiene",
    },
    {
        title: "Crypto Discipline",
        workspace: "Strategy Desk",
        operator: "Kat",
        briefing: "Inputs, spread, clock, and reference price remain visible before any trade story forms.",
        signal: "PRICE",
        cadence: "FAST",
        confidence: 76,
        accent: katechonTheme.amber,
        lens: "risk posture",
    },
    {
        title: "Deep Space",
        workspace: "Observatory",
        operator: "Kat",
        briefing: "Long-baseline anomalies, transit windows, and quiet telemetry arranged for patient reads.",
        signal: "COSMIC",
        cadence: "SLOW",
        confidence: 68,
        accent: "#b7a6ff",
        lens: "anomaly watch",
    },
    {
        title: "Power Grid",
        workspace: "Infrastructure",
        operator: "Kat",
        briefing: "Load balancing, cascade risk, and transmission stress organized into a steady command view.",
        signal: "GRID",
        cadence: "PULSE",
        confidence: 82,
        accent: "#a8ffef",
        lens: "stability",
    },
];
